name: Dustin Luke Nelson
favicon: null
layout_spectrum: 0.25368
typography_spectrum: 1
title: Dustin Luke Nelson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#332218'
    - '#694f38'
    - '#9b7c79'
    - '#c4beca'
    - '#dbd6dc'
  brandStrength: 0.9375
  lightness: 1
  saturation: 0.25
  rhythmicContrast: 0
purpose: []
