name: Dustin Luke Nelson
favicon: null
layout_spectrum: 0.7153782204259187
typography_spectrum: 0.6615727266762406
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#332218'
    - '#694f38'
    - '#9b7c79'
    - '#c4beca'
    - '#dbd6dc'
  brandStrength: 0.9375
  lightness: 0.7303053103387356
  saturation: 0.1173744082916528
  rhythmicContrast: 0.8711624555289745
purpose: []
