typography_spectrum: 1
color:
  brandColors:
    - '#182923'
    - '#84adb8'
    - '#2f453e'
    - '#466156'
    - '#c7d4c5'
  brandStrength: 0.0625
  lightness: 0.375
  saturation: 0.75
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Dustin Nelson
  email: dlukenelson@gmail.com
  url: 'http://www.dustinlukenelson.com'
name: Dustin Luke Nelson
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Performance
    id: 88a4a062-40ae-4167-b684-9b1bf77f7203
    type: content
favicon: null
title: Dustin Luke Nelson
purpose: []
