name: Dustin Luke Nelson
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Dustin Luke Nelson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#706a6a'
    - '#3a3f40'
    - '#090b0a'
    - '#a83e45'
    - '#ffffff'
  brandStrength: 0.75
  lightness: 0.3125
  saturation: 0
  rhythmicContrast: 0
purpose: []
